# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags: [ "v3.1.1*" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: |
          build() {
            export GOOS=$1
            export GOARCH=$2
            export CGO_ENABLED=0
            go build -ldflags "-s -w" -o release/moredoc-${1}-${2}${3} main.go
          }
          build linux arm64
          build linux arm
          build linux amd64
          build windows amd64 .exe
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
       path: release/*
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: release/*
